apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.dockerAuth }}
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{.Values.appVersion}}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range $key, $value := .Values.regularEnvData }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}

        {{- range $key, $value := .Values.secretData }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.secretName }}
              key: {{ $key }}
        {{- end }}

        {{- range $key, $value := .Values.configData }}
        - name: {{ $key }}
          valueFrom: 
            configMapKeyRef:
              name: {{ $.Values.configMapName }}
              key: {{ $key }}
        {{- end }}
